package com.exarlabs.android.myrules.model.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.exarlabs.android.myrules.model.dao.Rule;

import com.exarlabs.android.myrules.model.dao.RuleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ruleDaoConfig;

    private final RuleDao ruleDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ruleDaoConfig = daoConfigMap.get(RuleDao.class).clone();
        ruleDaoConfig.initIdentityScope(type);

        ruleDao = new RuleDao(ruleDaoConfig, this);

        registerDao(Rule.class, ruleDao);
    }
    
    public void clear() {
        ruleDaoConfig.getIdentityScope().clear();
    }

    public RuleDao getRuleDao() {
        return ruleDao;
    }

}
