package com.exarlabs.android.myrules.model.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.exarlabs.android.myrules.business.rule.RuleComponentProperty;
// KEEP INCLUDES END


/**
 * Entity mapped to table "RULE_ACTION_PROPERTY".
 */
public class RuleActionProperty extends RuleComponentProperty {

    private Long id;
    /** Not-null value. */
    private String key;
    private String value;
    private Long actionId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RuleActionProperty() {
    }

    public RuleActionProperty(Long id) {
        this.id = id;
    }

    public RuleActionProperty(Long id, String key, String value, Long actionId) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.actionId = actionId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Long getActionId() {
        return actionId;
    }

    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
