package com.exarlabs.android.myrules.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.exarlabs.android.myrules.model.dao.RuleRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RULE_RECORD".
*/
public class RuleRecordDao extends AbstractDao<RuleRecord, Long> {

    public static final String TABLENAME = "RULE_RECORD";

    /**
     * Properties of entity RuleRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RuleName = new Property(1, String.class, "ruleName", false, "RULE_NAME");
        public final static Property State = new Property(2, int.class, "state", false, "STATE");
        public final static Property EventCode = new Property(3, int.class, "eventCode", false, "EVENT_CODE");
        public final static Property ConditionLinkId = new Property(4, Long.class, "conditionLinkId", false, "CONDITION_LINK_ID");
    };

    private DaoSession daoSession;


    public RuleRecordDao(DaoConfig config) {
        super(config);
    }
    
    public RuleRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RULE_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"RULE_NAME\" TEXT," + // 1: ruleName
                "\"STATE\" INTEGER NOT NULL ," + // 2: state
                "\"EVENT_CODE\" INTEGER NOT NULL ," + // 3: eventCode
                "\"CONDITION_LINK_ID\" INTEGER);"); // 4: conditionLinkId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RULE_RECORD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RuleRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String ruleName = entity.getRuleName();
        if (ruleName != null) {
            stmt.bindString(2, ruleName);
        }
        stmt.bindLong(3, entity.getState());
        stmt.bindLong(4, entity.getEventCode());
 
        Long conditionLinkId = entity.getConditionLinkId();
        if (conditionLinkId != null) {
            stmt.bindLong(5, conditionLinkId);
        }
    }

    @Override
    protected void attachEntity(RuleRecord entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RuleRecord readEntity(Cursor cursor, int offset) {
        RuleRecord entity = new RuleRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ruleName
            cursor.getInt(offset + 2), // state
            cursor.getInt(offset + 3), // eventCode
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // conditionLinkId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RuleRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRuleName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setState(cursor.getInt(offset + 2));
        entity.setEventCode(cursor.getInt(offset + 3));
        entity.setConditionLinkId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RuleRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RuleRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRuleConditionLinkDao().getAllColumns());
            builder.append(" FROM RULE_RECORD T");
            builder.append(" LEFT JOIN RULE_CONDITION_LINK T0 ON T.\"CONDITION_LINK_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RuleRecord loadCurrentDeep(Cursor cursor, boolean lock) {
        RuleRecord entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        RuleConditionLink ruleConditionLink = loadCurrentOther(daoSession.getRuleConditionLinkDao(), cursor, offset);
        entity.setRuleConditionLink(ruleConditionLink);

        return entity;    
    }

    public RuleRecord loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RuleRecord> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RuleRecord> list = new ArrayList<RuleRecord>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RuleRecord> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RuleRecord> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
