package com.exarlabs.android.myrules.model.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RULE_CONDITION_PROPERTY".
 */
public class RuleConditionProperty {

    private Long id;
    /** Not-null value. */
    private String key;
    private String value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RuleConditionProperty() {
    }

    public RuleConditionProperty(Long id) {
        this.id = id;
    }

    public RuleConditionProperty(Long id, String key, String value) {
        this.id = id;
        this.key = key;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
