package com.exarlabs.android.myrules.model.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.exarlabs.android.myrules.model.dao.RuleActionLink;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RULE_ACTION_LINK".
*/
public class RuleActionLinkDao extends AbstractDao<RuleActionLink, Long> {

    public static final String TABLENAME = "RULE_ACTION_LINK";

    /**
     * Properties of entity RuleActionLink.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RuleId = new Property(1, Long.class, "ruleId", false, "RULE_ID");
        public final static Property RuleRecordId = new Property(2, Long.class, "ruleRecordId", false, "RULE_RECORD_ID");
        public final static Property ActionId = new Property(3, Long.class, "actionId", false, "ACTION_ID");
        public final static Property RuleActionId = new Property(4, Long.class, "ruleActionId", false, "RULE_ACTION_ID");
    };

    private DaoSession daoSession;

    private Query<RuleActionLink> ruleRecord_RuleActionLinksQuery;
    private Query<RuleActionLink> ruleAction_RuleActionLinksQuery;

    public RuleActionLinkDao(DaoConfig config) {
        super(config);
    }
    
    public RuleActionLinkDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RULE_ACTION_LINK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"RULE_ID\" INTEGER," + // 1: ruleId
                "\"RULE_RECORD_ID\" INTEGER," + // 2: ruleRecordId
                "\"ACTION_ID\" INTEGER," + // 3: actionId
                "\"RULE_ACTION_ID\" INTEGER);"); // 4: ruleActionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RULE_ACTION_LINK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RuleActionLink entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long ruleId = entity.getRuleId();
        if (ruleId != null) {
            stmt.bindLong(2, ruleId);
        }
 
        Long ruleRecordId = entity.getRuleRecordId();
        if (ruleRecordId != null) {
            stmt.bindLong(3, ruleRecordId);
        }
 
        Long actionId = entity.getActionId();
        if (actionId != null) {
            stmt.bindLong(4, actionId);
        }
 
        Long ruleActionId = entity.getRuleActionId();
        if (ruleActionId != null) {
            stmt.bindLong(5, ruleActionId);
        }
    }

    @Override
    protected void attachEntity(RuleActionLink entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RuleActionLink readEntity(Cursor cursor, int offset) {
        RuleActionLink entity = new RuleActionLink( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // ruleId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // ruleRecordId
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // actionId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // ruleActionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RuleActionLink entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRuleId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setRuleRecordId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setActionId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setRuleActionId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RuleActionLink entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RuleActionLink entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "ruleActionLinks" to-many relationship of RuleRecord. */
    public List<RuleActionLink> _queryRuleRecord_RuleActionLinks(Long ruleId) {
        synchronized (this) {
            if (ruleRecord_RuleActionLinksQuery == null) {
                QueryBuilder<RuleActionLink> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RuleId.eq(null));
                ruleRecord_RuleActionLinksQuery = queryBuilder.build();
            }
        }
        Query<RuleActionLink> query = ruleRecord_RuleActionLinksQuery.forCurrentThread();
        query.setParameter(0, ruleId);
        return query.list();
    }

    /** Internal query to resolve the "ruleActionLinks" to-many relationship of RuleAction. */
    public List<RuleActionLink> _queryRuleAction_RuleActionLinks(Long actionId) {
        synchronized (this) {
            if (ruleAction_RuleActionLinksQuery == null) {
                QueryBuilder<RuleActionLink> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ActionId.eq(null));
                ruleAction_RuleActionLinksQuery = queryBuilder.build();
            }
        }
        Query<RuleActionLink> query = ruleAction_RuleActionLinksQuery.forCurrentThread();
        query.setParameter(0, actionId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRuleRecordDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getRuleActionDao().getAllColumns());
            builder.append(" FROM RULE_ACTION_LINK T");
            builder.append(" LEFT JOIN RULE_RECORD T0 ON T.\"RULE_RECORD_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN RULE_ACTION T1 ON T.\"RULE_ACTION_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RuleActionLink loadCurrentDeep(Cursor cursor, boolean lock) {
        RuleActionLink entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        RuleRecord ruleRecord = loadCurrentOther(daoSession.getRuleRecordDao(), cursor, offset);
        entity.setRuleRecord(ruleRecord);
        offset += daoSession.getRuleRecordDao().getAllColumns().length;

        RuleAction ruleAction = loadCurrentOther(daoSession.getRuleActionDao(), cursor, offset);
        entity.setRuleAction(ruleAction);

        return entity;    
    }

    public RuleActionLink loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RuleActionLink> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RuleActionLink> list = new ArrayList<RuleActionLink>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RuleActionLink> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RuleActionLink> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
