package com.exarlabs.android.myrules.model.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RULE".
 */
public class Rule {

    private Long id;
    private int state;
    private int eventCode;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Rule() {
    }

    public Rule(Long id) {
        this.id = id;
    }

    public Rule(Long id, int state, int eventCode) {
        this.id = id;
        this.state = state;
        this.eventCode = eventCode;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

    public int getEventCode() {
        return eventCode;
    }

    public void setEventCode(int eventCode) {
        this.eventCode = eventCode;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
