package com.exarlabs.android.myrules.model.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.exarlabs.android.myrules.model.dao.RuleConditionProperty;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RULE_CONDITION_PROPERTY".
*/
public class RuleConditionPropertyDao extends AbstractDao<RuleConditionProperty, Long> {

    public static final String TABLENAME = "RULE_CONDITION_PROPERTY";

    /**
     * Properties of entity RuleConditionProperty.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property Value = new Property(2, String.class, "value", false, "VALUE");
        public final static Property ConditionId = new Property(3, Long.class, "conditionId", false, "CONDITION_ID");
    };

    private Query<RuleConditionProperty> ruleCondition_PropertiesQuery;

    public RuleConditionPropertyDao(DaoConfig config) {
        super(config);
    }
    
    public RuleConditionPropertyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RULE_CONDITION_PROPERTY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"KEY\" TEXT NOT NULL ," + // 1: key
                "\"VALUE\" TEXT," + // 2: value
                "\"CONDITION_ID\" INTEGER);"); // 3: conditionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RULE_CONDITION_PROPERTY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RuleConditionProperty entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getKey());
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(3, value);
        }
 
        Long conditionId = entity.getConditionId();
        if (conditionId != null) {
            stmt.bindLong(4, conditionId);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RuleConditionProperty readEntity(Cursor cursor, int offset) {
        RuleConditionProperty entity = new RuleConditionProperty( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // key
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // value
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // conditionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RuleConditionProperty entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getString(offset + 1));
        entity.setValue(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setConditionId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RuleConditionProperty entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RuleConditionProperty entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "properties" to-many relationship of RuleCondition. */
    public List<RuleConditionProperty> _queryRuleCondition_Properties(Long conditionId) {
        synchronized (this) {
            if (ruleCondition_PropertiesQuery == null) {
                QueryBuilder<RuleConditionProperty> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ConditionId.eq(null));
                ruleCondition_PropertiesQuery = queryBuilder.build();
            }
        }
        Query<RuleConditionProperty> query = ruleCondition_PropertiesQuery.forCurrentThread();
        query.setParameter(0, conditionId);
        return query.list();
    }

}
